#!/bin/sh
# /etc/init.d/alfred
#
### BEGIN INIT INFO
# Provides:           alfred
# Required-Start:     $local_fs $netork $syslog
# Required-Start:     $local_fs $netork $syslog
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# X-Interactive:      false
# Short-Description:  starts alfred daemon
# Description:        starts alfred daemon
### END INIT INFO

DESC="Almighty Lightweight Fact Remote Exchange Daemon"
NAME="afred"
DAEMON=/usr/local/sbin/$NAME

source /etc/alfred.conf

case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"

    # start alfred on specified interface
    alfred -i $INTERFACE

    # switch to master mode
    if [[ "$MASTER" == 1 ]]; then
      alfred -M master
    fi
    ;;
  stop)
    echo "Stopping alfred daemon"
    ;;
  *)
    echo "Usage: /etc/init.d/alfred {start|stop}"
    exit 1
    ;;
esac

exit 0
